language: node_js
node_js:
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-dsg-component' ]; then cd .. && eval "mv $currentfolder generator-dsg-component" && cd generator-dsg-component; fi

